<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/varundudeja/Documents/desi-world/static/models/desi-world/Plane.glb --transform
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';
	import { onMount } from 'svelte';
	import { isPlane } from '$lib/stores/commonStores';

	export const ref = new Group();

	const gltf = useGltf('/models/desi-world/Plane-transformed.glb', { useDraco: true });
	const gltf2 = useGltf('/models/desi-world/Plane-transformed.glb', { useDraco: true }).then(
		(res) => {
			$isPlane = true;
		}
	);

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<AutoColliders shape={'trimesh'}>
			<T.Mesh geometry={gltf.nodes.Plane001.geometry} material={gltf.materials.MyGround} />
		</AutoColliders>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
