<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 /Users/varundudeja/Documents/desi-world/static/models/desi-world/Walls.glb --transform
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { AutoColliders } from '@threlte/rapier';

	export const ref = new Group();

	const gltf = useGltf('/models/desi-world/Walls-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<AutoColliders shape={'trimesh'}>
			<T.Mesh geometry={gltf.nodes.Walls.geometry} material={gltf.materials.WoodTexture} />
		</AutoColliders>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
